-- Create services directly using random UUIDs for existing users
-- We'll create placeholder services that can be easily updated

INSERT INTO services (
  provider_id,
  title,
  description,
  category,
  price_zar,
  price_wellcoins,
  duration_minutes,
  location,
  is_online,
  images,
  active
) VALUES
-- FACT Wellness Services (using placeholder provider_id that needs to be updated)
(
  gen_random_uuid(),
  'Hatha Yoga Class (Level 1)',
  'Traditional Hatha yoga class perfect for beginners. Hybrid format allows you to join in-person or online with expert instructors projected in our studio. Led by Chad Cupido at FACT WELLNESS.',
  'Yoga',
  75,
  15,
  60,
  '150 Main Road, Muizenberg',
  true,
  ARRAY[],
  true
),
(
  gen_random_uuid(),
  'QiGong Practice (Level 1)',
  'Gentle flowing movements combining breath, movement, and meditation. Improve your energy levels and reduce stress with this ancient Chinese practice. FACT WELLNESS hybrid experience.',
  'QiGong',
  75,
  15,
  60,
  '150 Main Road, Muizenberg',
  true,
  ARRAY[],
  true
),
(
  gen_random_uuid(),
  'Mantra Chanting & Guided Meditation',
  'Start your day with powerful mantra chanting and guided meditation. Improve mental clarity, focus, and inner peace. FACT WELLNESS morning practice.',
  'Meditation',
  75,
  15,
  60,
  '150 Main Road, Muizenberg',
  true,
  ARRAY[],
  true
),
(
  gen_random_uuid(),
  'Yoga & Pilates Fusion Flow',
  'Dynamic fusion class combining the strength of Pilates with the flexibility of yoga. Suitable for intermediate practitioners. FACT WELLNESS signature class.',
  'Pilates',
  75,
  15,
  60,
  '150 Main Road, Muizenberg',
  false,
  ARRAY[],
  true
),
(
  gen_random_uuid(),
  'Vinyasa Flow Yoga',
  'Energizing vinyasa flow connecting breath with movement. Perfect for building strength and flexibility. FACT WELLNESS Sunday special.',
  'Yoga',
  75,
  15,
  90,
  '150 Main Road, Muizenberg',
  true,
  ARRAY[],
  true
),
(
  gen_random_uuid(),
  '5 Class Pass - FACT WELLNESS',
  'Save with our 5 class pass. Valid for any yoga, QiGong, Pilates, or meditation classes. Expires in 2 months. Great value package.',
  'Yoga',
  300,
  60,
  0,
  '150 Main Road, Muizenberg',
  true,
  ARRAY[],
  true
),
(
  gen_random_uuid(),
  'Monthly Unlimited Pass - FACT WELLNESS',
  'Unlimited access to all classes for one month. Perfect for dedicated practitioners wanting maximum flexibility and value.',
  'Yoga',
  500,
  100,
  0,
  '150 Main Road, Muizenberg',
  true,
  ARRAY[],
  true
),
-- Travel and Tours Cape Town Services
(
  gen_random_uuid(),
  'Great Mother Cave Tour',
  'Discover sacred sites of Peers Cave and Tunnel Cave with Chief Kingsley. Full day immersive journey into Khoisan spiritual traditions and ancient wisdom. Travel and Tours Cape Town signature experience.',
  'Life Coaching',
  2999,
  600,
  480,
  'Fish Hoek, Cape Town',
  false,
  ARRAY[],
  true
),
(
  gen_random_uuid(),
  'Kalk Bay Indigenous Walk',
  'Cultural and natural odyssey through Kalk Bay with Chief Kingsley. Explore Echo Valley, Boomslang Cave, and learn indigenous plant medicine. Transformative cultural experience.',
  'Life Coaching',
  1499,
  300,
  240,
  'Kalk Bay, Cape Town',
  false,
  ARRAY[],
  true
),
(
  gen_random_uuid(),
  'Cape Summit Adventure',
  'Conquer Table Mountain and Lion Head with expert guides. Combine physical challenge with cultural insights and breathtaking views. Adventure tourism at its finest.',
  'Personal Training',
  2499,
  500,
  480,
  'Table Mountain, Cape Town',
  false,
  ARRAY[],
  true
),
(
  gen_random_uuid(),
  'Ultimate Surf & Culture Experience',
  'Ride waves with world champion Cass Collier. Combine surfing instruction with cultural immersion and ocean blessing ceremonies. Unique Muizenberg experience.',
  'Personal Training',
  2999,
  600,
  480,
  'Muizenberg Beach, Cape Town',
  false,
  ARRAY[],
  true
),
(
  gen_random_uuid(),
  'Indigenous Healing Immersion',
  '7-day wellness retreat combining traditional healing ceremonies, plant medicine workshops, and indigenous wellness practices. Deep transformation experience.',
  'Massage Therapy',
  18999,
  3800,
  10080,
  'Cape Town & Surrounding Areas',
  false,
  ARRAY[],
  true
),
(
  gen_random_uuid(),
  'Ubuntu Leadership Retreat',
  '5-day transformational retreat applying Ubuntu philosophy to organizational leadership. Perfect for teams and leaders seeking conscious leadership development.',
  'Life Coaching',
  15999,
  3200,
  7200,
  'Cape Town & Surrounding Areas',
  false,
  ARRAY[],
  true
);