-- Add sample media for Sandy
INSERT INTO provider_media (provider_id, title, description, media_type, media_url, thumbnail_url, featured, active) VALUES
('351e4f5a-a27f-4fe5-957f-fa0ea1210040', 'Dru Yoga Introduction', 'A gentle introduction to Dru Yoga principles and basic movements', 'video', 'https://example.com/sandy-yoga-intro.mp4', 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=400', true, true),
('351e4f5a-a27f-4fe5-957f-fa0ea1210040', 'Breathing Exercise Demo', 'Demonstration of core Buteyko breathing techniques', 'video', 'https://example.com/sandy-breathing.mp4', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400', true, true),
('351e4f5a-a27f-4fe5-957f-fa0ea1210040', 'Wellness Studio Space', 'A look inside my peaceful yoga and healing studio', 'image', 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=800', null, false, true),
('351e4f5a-a27f-4fe5-957f-fa0ea1210040', 'Morning Practice', 'Starting the day with mindful movement and breath', 'image', 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800', null, false, true);

-- Add sample testimonials for Sandy
INSERT INTO provider_testimonials (provider_id, client_name, client_image_url, testimonial_text, rating, service_type, featured, approved) VALUES
('351e4f5a-a27f-4fe5-957f-fa0ea1210040', 'Sarah Thompson', 'https://images.unsplash.com/photo-1494790108755-2616b9c3b7cd?w=100', 'Sandy''s Dru Yoga classes have been transformative for me. Her gentle approach and focus on breath awareness helped me reconnect with my body after years of stress. I feel more grounded and peaceful after every session.', 5, 'Dru Yoga Class', true, true),
('351e4f5a-a27f-4fe5-957f-fa0ea1210040', 'Michael Chen', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100', 'The Buteyko breathing sessions with Sandy have dramatically improved my sleep and reduced my anxiety. She creates such a safe, non-judgmental space where healing can happen naturally.', 5, 'Buteyko Breathing', true, true),
('351e4f5a-a27f-4fe5-957f-fa0ea1210040', 'Emma Wilson', 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100', 'I''ve been attending Sandy''s classes for 6 months now. Her approach is so refreshing - no pressure, just gentle guidance back to yourself. The Mental Wellness course was particularly helpful during a difficult time.', 4, 'Mental Wellness Course', false, true);

-- Add sample blog posts for Sandy
INSERT INTO provider_posts (provider_id, title, slug, content, excerpt, featured_image_url, category, published, featured) VALUES
('351e4f5a-a27f-4fe5-957f-fa0ea1210040', 'The Gentle Power of Dru Yoga', 'gentle-power-dru-yoga', 'Dru Yoga is more than just physical postures - it''s a journey of self-discovery through gentle movement, breath awareness, and heart-based intention. In this practice, we don''t push or strive; instead, we soften and allow...', 'Discover how Dru Yoga''s gentle approach can transform your relationship with movement and breath.', 'https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=600', 'Yoga & Movement', true, true),
('351e4f5a-a27f-4fe5-957f-fa0ea1210040', 'Breathing Your Way to Better Sleep', 'breathing-better-sleep', 'Sleep issues often stem from dysfunctional breathing patterns developed through stress and modern living. The Buteyko Method offers a science-based approach to retraining your breath for deeper, more restorative sleep...', 'Learn how simple breathing techniques can revolutionize your sleep quality.', 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600', 'Breathwork', true, false),
('351e4f5a-a27f-4fe5-957f-fa0ea1210040', 'Creating Sacred Space for Healing', 'creating-sacred-space-healing', 'Whether in a studio or your living room, the space we practice in matters. It''s not about having perfect equipment or expensive props - it''s about intention, presence, and creating an environment where healing can unfold naturally...', 'Transform any space into a sanctuary for your wellness practice.', 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600', 'Wellness Tips', true, false);

-- Create Sandy's website
INSERT INTO provider_websites (provider_id, page_title, page_subtitle, about_section, published) VALUES
('351e4f5a-a27f-4fe5-957f-fa0ea1210040', 'Sandy Mitchell Wellness', 'Heart-based healing through gentle movement and conscious breath', 'Welcome to a space where healing happens naturally. I''m Sandy Mitchell, and I believe that true wellness comes from within - from reconnecting with our breath, our bodies, and our innate wisdom. Through Dru Yoga and Buteyko Breathing, I guide others back to themselves with tenderness and respect for where they are in their journey.', true);