INSERT INTO public.outreach_leads (organisation,sector,contact_method,contact_email,contact_person,programme,website,csr_url,status,campaign,last_contacted,follow_up_due,notes) VALUES
('Old Mutual','Corporate CSI','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('MTN','Corporate CSI','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('Momentum Metropolitan','Corporate CSI','Declined',NULL,NULL,NULL,NULL,NULL,'declined','overall',NULL,NULL,'Not accepting NPOs currently'),
('Engen','Corporate CSI','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('Toyota','Corporate CSI','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('Toyota Online','Corporate CSI','Online Application',NULL,NULL,NULL,NULL,NULL,'awaiting','overall',NULL,'2026-04-10','Application submitted - awaiting feedback'),
('The Vineyard Hotel','Hospitality / CSR','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('Vida e Caffè','Corporate Social Investment','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('Exclusive Books','Retail','Phone / Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'Office closed when contacted - revisit'),
('Telkom CSI','Tech / Corporate CSI','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('V&A Waterfront Community Team','Community Engagement','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('PNA','Retail / Education','Positive',NULL,NULL,NULL,NULL,NULL,'positive','overall',NULL,NULL,'Replied — awaiting next steps'),
('Global Kinetic','Tech','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('Khanyisa Real Systems','Tech','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('SOLIDitech','Tech','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('Bluegrass Digital','Tech','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('DVT','Tech','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('Drakkentech','Tech','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('Digita','Tech','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('Wave Technologies','Tech','Email',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'No Response'),
('FNB','Corporate CSI','Redirected',NULL,NULL,NULL,NULL,NULL,'declined','overall',NULL,NULL,'Legal/IP restrictions'),
('Makro','Corporate CSI','Redirected',NULL,NULL,NULL,NULL,NULL,'no_response','overall',NULL,NULL,'Redirected — now no response'),
('Clicks','Corporate CSI','Redirected',NULL,NULL,NULL,NULL,NULL,'awaiting','overall',NULL,NULL,'Prep Application'),
('Dis-Chem','Corporate CSI','Declined',NULL,NULL,NULL,NULL,NULL,'declined','overall',NULL,NULL,'Not accepting NPOs - revisit this year'),
('Softserve','Tech','Positive',NULL,NULL,NULL,NULL,NULL,'positive','overall',NULL,NULL,'Awaiting follow up'),
('AWS Academy (Amazon)','Tech / Education','Online Application',NULL,NULL,NULL,NULL,NULL,'declined','overall',NULL,NULL,'Application declined'),
('Sanlam Grants','Corporate CSI','Online Application',NULL,NULL,NULL,NULL,NULL,'declined','overall',NULL,NULL,'Requires 3+ years registration'),
('HCI Foundation','Corporate CSI','Online Application',NULL,NULL,NULL,NULL,NULL,'declined','overall',NULL,NULL,'No applications due to budget'),
('KFC Foundation','Corporate CSI','Online Application',NULL,NULL,NULL,NULL,NULL,'declined','overall',NULL,NULL,'Requires 3+ years registration'),
('San Foundation','NGO','Online Application',NULL,NULL,NULL,NULL,NULL,'awaiting','overall',NULL,NULL,'Successfully registered - awaiting feedback'),
('Shoprite Donation / Sponsorship','Corporate CSI','Online Application',NULL,NULL,NULL,NULL,NULL,'awaiting','overall',NULL,NULL,'Reference: DS#30866 - awaiting feedback'),
('Raith Foundation - Overall','NGO','Online Application',NULL,NULL,NULL,NULL,NULL,'awaiting','overall',NULL,'2026-03-31','Applications open 1 Feb - 31 March'),
('DGMT Portal','Grant Platform','Online Application',NULL,NULL,NULL,NULL,NULL,'awaiting','overall',NULL,'2026-04-17','Login obtained - online application 13-17 April'),
('IDC','Corporate CSI','Email',NULL,NULL,NULL,NULL,NULL,'contacted','overall','2026-05-07',NULL,'07 May - Sent'),
('Novus','Corporate CSI','Email',NULL,NULL,NULL,NULL,NULL,'contacted','overall','2026-05-07',NULL,'07 May - Sent'),
('International Hotel School','Hospitality/Education','Email','online@hotelschool.co.za',NULL,NULL,NULL,NULL,'contacted','zacri','2026-01-26','2026-02-06','Initial email sent'),
('Infinity Culinary Training','Hospitality/Education','Email','ntombi@ictchefs.org',NULL,NULL,NULL,NULL,'contacted','zacri','2026-01-26','2026-02-06','Initial email sent'),
('Capsicum Culinary Studio','Hospitality/Education','Email','info@capsicumcooking.com',NULL,NULL,NULL,NULL,'contacted','zacri','2026-01-26','2026-02-06','Initial email sent'),
('Plant Cafe','Hospitality/Education','Email','pierre@plantcafe.co.za',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-03','2026-02-09','Initial email sent'),
('Wild Eatery','Hospitality/Education','Email','wildeaterycpt@gmail.com',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-03','2026-02-09','Initial email sent'),
('Wildsprout','Hospitality/Education','Email','info@wsprout.co.za',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-03','2026-02-09','Initial email sent'),
('Romeo & Vero','Hospitality/Education','Email','romeomujinga14@gmail.com',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-04','2026-02-09','Initial email sent'),
('Taj Hotel','Hospitality/Education','Email','contacttaj@tajhotels.com',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-04','2026-02-09','Initial email sent'),
('Raddison Red Hotel','Hospitality/Education','Email','baxter@radissonred.com',NULL,NULL,NULL,NULL,'declined','zacri','2026-02-04',NULL,'Funding Denied (Internship opportunity)'),
('Southern Sun Hotel','Hospitality/Education','Email','sscullinan.reservations@southernsun.com',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-04','2026-02-09','Initial email sent'),
('Hotel Verde','Hospitality/Education','Email','reservations@hotelverde.com',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-04','2026-02-09','Initial email sent'),
('Cape Grace Hotel','Hospitality/Education','Email','capegrace.info@fairmont.com',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-04','2026-02-09','Initial email sent'),
('False Bay TVET College','Hospitality/Education','Email','info@falsebay.org.za',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-03',NULL,'Initial Mail Sent'),
('Tigers Milk Muizenberg','Hospitality/Education','Email','muizenberg@tigersmilk.co.za',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-03',NULL,'Initial Mail Sent'),
('Olympia Cafe & Bakery','Hospitality/Education','Email','info@olympiacafe.co.za',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-03','2026-02-09','Initial Mail Sent'),
('Woolworths CSI / MySchool','Hospitality/Education','Email','cs@myschool.co.za',NULL,NULL,NULL,NULL,'declined','zacri','2026-02-03',NULL,'Declined'),
('Chef Skill Development','Hospitality/Education','Email','info@chefskillsdevelopment.co.za',NULL,NULL,NULL,NULL,'declined','zacri','2026-02-03',NULL,'Declined'),
('Peermont Education Trust','Hospitality/Education','Email','info@peermont.com',NULL,NULL,NULL,NULL,'declined','zacri','2026-02-03',NULL,'Declined'),
('Knead Bakery','Hospitality/Education','Email','ctkitchenorders@seattleco.com',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-03','2026-02-09','Initial Mail Sent'),
('City Sightseeing Cape Town CSI','Hospitality/Education','Email','info@citysightseeing.co.za',NULL,NULL,NULL,NULL,'contacted','zacri','2026-02-03','2026-02-09','Initial Mail Sent'),
('Laureus Sport for Good','Youth Sports','Email','info@sportforgood.org','Programme Director','Youth Sports','https://www.laureus.com/sport-for-good','https://www.laureus.com/sport-for-good','no_response','youth_sports',NULL,NULL,NULL),
('Western Cape Dept of Cultural Affairs and Sport','Youth Sports','Email','dcas@westerncape.gov.za','Community Sport Director','Youth Sports','https://www.westerncape.gov.za/dept/cas','https://www.westerncape.gov.za/dept/cas','no_response','youth_sports',NULL,NULL,NULL),
('Adidas Foundation','Youth & Sport','Email','foundation@adidas-group.com','Foundation Partnerships','Youth & Sport','https://www.adidas-group.com/en/sustainability/people/','https://www.adidas-group.com/en/sustainability/people/','no_response','youth_sports',NULL,NULL,NULL),
('Raith Foundation','Women & Youth','Email','info@raithfoundation.org','Programme Officer','Women & Youth','https://www.raithfoundation.org','https://www.raithfoundation.org/apply','no_response','women',NULL,NULL,NULL),
('Elma Foundation','Women & Youth','Email','info@elmafoundation.org','Grants Manager','Women & Youth','https://elmafoundation.org','https://elmafoundation.org','no_response','women',NULL,NULL,NULL),
('UN Women South Africa','Women Empowerment','Email','registry.southafrica@unwomen.org','Programme Officer','Women Empowerment','https://southafrica.unwomen.org','https://southafrica.unwomen.org/en/partnerships','no_response','women',NULL,NULL,NULL),
('DG Murray Trust','ECD & Literacy','Email','info@dgmt.co.za','Programme Manager','ECD & Literacy','https://dgmt.co.za','https://dgmt.co.za/funding/','no_response','ecd',NULL,NULL,NULL),
('Nalibali Reading Campaign','Reading & Literacy','Email','info@nalibali.org','Partnerships Lead','Reading & Literacy','https://nalibali.org','https://nalibali.org/get-involved/','no_response','ecd',NULL,NULL,NULL),
('Zenex Foundation','Education','Email','info@zenexfoundation.org.za','Foundation Manager','Education','https://zenexfoundation.org.za','https://zenexfoundation.org.za/apply-for-funding/','no_response','ecd',NULL,NULL,NULL),
('Google for Nonprofits','Tech & Connectivity','Email','nonprofits@google.com','Nonprofit Partnerships Team','Tech & Connectivity','https://www.google.com/nonprofits/','https://www.google.com/nonprofits/','no_response','tech',NULL,NULL,NULL),
('Microsoft Philanthropies','Tech & Devices','Email','nonprofit@microsoft.com','Nonprofit Program Manager','Tech & Devices','https://www.microsoft.com/philanthropies','https://www.microsoft.com/philanthropies/nonprofits','no_response','tech',NULL,NULL,NULL),
('Dell Technologies Social Impact','Tech & Equipment','Email','social_impact@dell.com','Social Impact Team','Tech & Equipment','https://www.dell.com/en-za/dt/corporate/social-impact.htm','https://www.dell.com/en-za/dt/corporate/social-impact.htm','no_response','tech',NULL,NULL,NULL);